/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedQuickRepliesRouteImport } from './routes/_authenticated.quick-replies'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedFunnelsRouteImport } from './routes/_authenticated.funnels'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated.channels'
import { Route as AuthenticatedCascadesRouteImport } from './routes/_authenticated.cascades'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated.campaigns'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated.team.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated.inbox.index'
import { Route as AuthenticatedFlowsIndexRouteImport } from './routes/_authenticated.flows.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated.crm.index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated.agents.index'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicMetricsRouteImport } from './routes/api/public/metrics'
import { Route as ApiPublicLiveRouteImport } from './routes/api/public/live'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicGuardianCronRouteImport } from './routes/api/public/guardian-cron'
import { Route as ApiPublicFlowResumeRouteImport } from './routes/api/public/flow-resume'
import { Route as AuthenticatedTeamRolesRouteImport } from './routes/_authenticated.team.roles'
import { Route as AuthenticatedTeamMemberIdRouteImport } from './routes/_authenticated.team.$memberId'
import { Route as AuthenticatedSettingsFeaturesRouteImport } from './routes/_authenticated.settings.features'
import { Route as AuthenticatedSettingsFeatureFlagsRouteImport } from './routes/_authenticated.settings.feature-flags'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated.settings.audit'
import { Route as AuthenticatedReportsConversationsRouteImport } from './routes/_authenticated.reports.conversations'
import { Route as AuthenticatedReportsCascadesRouteImport } from './routes/_authenticated.reports.cascades'
import { Route as AuthenticatedReportsBroadcastsRouteImport } from './routes/_authenticated.reports.broadcasts'
import { Route as AuthenticatedInboxConversationIdRouteImport } from './routes/_authenticated.inbox.$conversationId'
import { Route as AuthenticatedFlowsFlowIdRouteImport } from './routes/_authenticated.flows.$flowId'
import { Route as AuthenticatedCrmContactIdRouteImport } from './routes/_authenticated.crm.$contactId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated.agents.$agentId'
import { Route as ApiPublicHooksWhatsappWebhookRouteImport } from './routes/api/public/hooks/whatsapp-webhook'
import { Route as ApiPublicCronCascadeTickRouteImport } from './routes/api/public/cron/cascade-tick'
import { Route as AuthenticatedFlowsFlowIdRunsRouteImport } from './routes/_authenticated.flows.$flowId.runs'
import { Route as ApiPublicWebhooksWhatsappChannelIdRouteImport } from './routes/api/public/webhooks/whatsapp.$channelId'
import { Route as ApiPublicWebhooksStevoChannelIdRouteImport } from './routes/api/public/webhooks/stevo.$channelId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuickRepliesRoute =
  AuthenticatedQuickRepliesRouteImport.update({
    id: '/quick-replies',
    path: '/quick-replies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFunnelsRoute = AuthenticatedFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCascadesRoute = AuthenticatedCascadesRouteImport.update({
  id: '/cascades',
  path: '/cascades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedFlowsIndexRoute = AuthenticatedFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveRoute = ApiPublicLiveRouteImport.update({
  id: '/api/public/live',
  path: '/api/public/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuardianCronRoute = ApiPublicGuardianCronRouteImport.update({
  id: '/api/public/guardian-cron',
  path: '/api/public/guardian-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlowResumeRoute = ApiPublicFlowResumeRouteImport.update({
  id: '/api/public/flow-resume',
  path: '/api/public/flow-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRolesRoute = AuthenticatedTeamRolesRouteImport.update({
  id: '/team/roles',
  path: '/team/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamMemberIdRoute =
  AuthenticatedTeamMemberIdRouteImport.update({
    id: '/team/$memberId',
    path: '/team/$memberId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFeaturesRoute =
  AuthenticatedSettingsFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFeatureFlagsRoute =
  AuthenticatedSettingsFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReportsConversationsRoute =
  AuthenticatedReportsConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCascadesRoute =
  AuthenticatedReportsCascadesRouteImport.update({
    id: '/cascades',
    path: '/cascades',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsBroadcastsRoute =
  AuthenticatedReportsBroadcastsRouteImport.update({
    id: '/broadcasts',
    path: '/broadcasts',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedInboxConversationIdRoute =
  AuthenticatedInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)
const AuthenticatedFlowsFlowIdRoute =
  AuthenticatedFlowsFlowIdRouteImport.update({
    id: '/flows/$flowId',
    path: '/flows/$flowId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmContactIdRoute =
  AuthenticatedCrmContactIdRouteImport.update({
    id: '/crm/$contactId',
    path: '/crm/$contactId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksWhatsappWebhookRoute =
  ApiPublicHooksWhatsappWebhookRouteImport.update({
    id: '/api/public/hooks/whatsapp-webhook',
    path: '/api/public/hooks/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCascadeTickRoute =
  ApiPublicCronCascadeTickRouteImport.update({
    id: '/api/public/cron/cascade-tick',
    path: '/api/public/cron/cascade-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFlowsFlowIdRunsRoute =
  AuthenticatedFlowsFlowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedFlowsFlowIdRoute,
  } as any)
const ApiPublicWebhooksWhatsappChannelIdRoute =
  ApiPublicWebhooksWhatsappChannelIdRouteImport.update({
    id: '/api/public/webhooks/whatsapp/$channelId',
    path: '/api/public/webhooks/whatsapp/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStevoChannelIdRoute =
  ApiPublicWebhooksStevoChannelIdRouteImport.update({
    id: '/api/public/webhooks/stevo/$channelId',
    path: '/api/public/webhooks/stevo/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/cascades': typeof AuthenticatedCascadesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/funnels': typeof AuthenticatedFunnelsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/quick-replies': typeof AuthenticatedQuickRepliesRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/crm/$contactId': typeof AuthenticatedCrmContactIdRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRouteWithChildren
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/reports/broadcasts': typeof AuthenticatedReportsBroadcastsRoute
  '/reports/cascades': typeof AuthenticatedReportsCascadesRoute
  '/reports/conversations': typeof AuthenticatedReportsConversationsRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/feature-flags': typeof AuthenticatedSettingsFeatureFlagsRoute
  '/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/team/roles': typeof AuthenticatedTeamRolesRoute
  '/api/public/flow-resume': typeof ApiPublicFlowResumeRoute
  '/api/public/guardian-cron': typeof ApiPublicGuardianCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/flows/': typeof AuthenticatedFlowsIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/flows/$flowId/runs': typeof AuthenticatedFlowsFlowIdRunsRoute
  '/api/public/cron/cascade-tick': typeof ApiPublicCronCascadeTickRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
  '/api/public/webhooks/stevo/$channelId': typeof ApiPublicWebhooksStevoChannelIdRoute
  '/api/public/webhooks/whatsapp/$channelId': typeof ApiPublicWebhooksWhatsappChannelIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/cascades': typeof AuthenticatedCascadesRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/funnels': typeof AuthenticatedFunnelsRoute
  '/quick-replies': typeof AuthenticatedQuickRepliesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/crm/$contactId': typeof AuthenticatedCrmContactIdRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRouteWithChildren
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/reports/broadcasts': typeof AuthenticatedReportsBroadcastsRoute
  '/reports/cascades': typeof AuthenticatedReportsCascadesRoute
  '/reports/conversations': typeof AuthenticatedReportsConversationsRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/feature-flags': typeof AuthenticatedSettingsFeatureFlagsRoute
  '/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/team/roles': typeof AuthenticatedTeamRolesRoute
  '/api/public/flow-resume': typeof ApiPublicFlowResumeRoute
  '/api/public/guardian-cron': typeof ApiPublicGuardianCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/flows': typeof AuthenticatedFlowsIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/flows/$flowId/runs': typeof AuthenticatedFlowsFlowIdRunsRoute
  '/api/public/cron/cascade-tick': typeof ApiPublicCronCascadeTickRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
  '/api/public/webhooks/stevo/$channelId': typeof ApiPublicWebhooksStevoChannelIdRoute
  '/api/public/webhooks/whatsapp/$channelId': typeof ApiPublicWebhooksWhatsappChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/cascades': typeof AuthenticatedCascadesRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/funnels': typeof AuthenticatedFunnelsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/quick-replies': typeof AuthenticatedQuickRepliesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/crm/$contactId': typeof AuthenticatedCrmContactIdRoute
  '/_authenticated/flows/$flowId': typeof AuthenticatedFlowsFlowIdRouteWithChildren
  '/_authenticated/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/_authenticated/reports/broadcasts': typeof AuthenticatedReportsBroadcastsRoute
  '/_authenticated/reports/cascades': typeof AuthenticatedReportsCascadesRoute
  '/_authenticated/reports/conversations': typeof AuthenticatedReportsConversationsRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/feature-flags': typeof AuthenticatedSettingsFeatureFlagsRoute
  '/_authenticated/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/_authenticated/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/_authenticated/team/roles': typeof AuthenticatedTeamRolesRoute
  '/api/public/flow-resume': typeof ApiPublicFlowResumeRoute
  '/api/public/guardian-cron': typeof ApiPublicGuardianCronRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/live': typeof ApiPublicLiveRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/flows/': typeof AuthenticatedFlowsIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/flows/$flowId/runs': typeof AuthenticatedFlowsFlowIdRunsRoute
  '/api/public/cron/cascade-tick': typeof ApiPublicCronCascadeTickRoute
  '/api/public/hooks/whatsapp-webhook': typeof ApiPublicHooksWhatsappWebhookRoute
  '/api/public/webhooks/stevo/$channelId': typeof ApiPublicWebhooksStevoChannelIdRoute
  '/api/public/webhooks/whatsapp/$channelId': typeof ApiPublicWebhooksWhatsappChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/cascades'
    | '/channels'
    | '/funnels'
    | '/inbox'
    | '/quick-replies'
    | '/reports'
    | '/settings'
    | '/invite/$token'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/flows/$flowId'
    | '/inbox/$conversationId'
    | '/reports/broadcasts'
    | '/reports/cascades'
    | '/reports/conversations'
    | '/settings/audit'
    | '/settings/feature-flags'
    | '/settings/features'
    | '/team/$memberId'
    | '/team/roles'
    | '/api/public/flow-resume'
    | '/api/public/guardian-cron'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/agents/'
    | '/crm/'
    | '/flows/'
    | '/inbox/'
    | '/reports/'
    | '/settings/'
    | '/team/'
    | '/flows/$flowId/runs'
    | '/api/public/cron/cascade-tick'
    | '/api/public/hooks/whatsapp-webhook'
    | '/api/public/webhooks/stevo/$channelId'
    | '/api/public/webhooks/whatsapp/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/campaigns'
    | '/cascades'
    | '/channels'
    | '/funnels'
    | '/quick-replies'
    | '/invite/$token'
    | '/'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/flows/$flowId'
    | '/inbox/$conversationId'
    | '/reports/broadcasts'
    | '/reports/cascades'
    | '/reports/conversations'
    | '/settings/audit'
    | '/settings/feature-flags'
    | '/settings/features'
    | '/team/$memberId'
    | '/team/roles'
    | '/api/public/flow-resume'
    | '/api/public/guardian-cron'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/agents'
    | '/crm'
    | '/flows'
    | '/inbox'
    | '/reports'
    | '/settings'
    | '/team'
    | '/flows/$flowId/runs'
    | '/api/public/cron/cascade-tick'
    | '/api/public/hooks/whatsapp-webhook'
    | '/api/public/webhooks/stevo/$channelId'
    | '/api/public/webhooks/whatsapp/$channelId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/cascades'
    | '/_authenticated/channels'
    | '/_authenticated/funnels'
    | '/_authenticated/inbox'
    | '/_authenticated/quick-replies'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/_authenticated/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/crm/$contactId'
    | '/_authenticated/flows/$flowId'
    | '/_authenticated/inbox/$conversationId'
    | '/_authenticated/reports/broadcasts'
    | '/_authenticated/reports/cascades'
    | '/_authenticated/reports/conversations'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/feature-flags'
    | '/_authenticated/settings/features'
    | '/_authenticated/team/$memberId'
    | '/_authenticated/team/roles'
    | '/api/public/flow-resume'
    | '/api/public/guardian-cron'
    | '/api/public/health'
    | '/api/public/live'
    | '/api/public/metrics'
    | '/api/public/ready'
    | '/_authenticated/agents/'
    | '/_authenticated/crm/'
    | '/_authenticated/flows/'
    | '/_authenticated/inbox/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/team/'
    | '/_authenticated/flows/$flowId/runs'
    | '/api/public/cron/cascade-tick'
    | '/api/public/hooks/whatsapp-webhook'
    | '/api/public/webhooks/stevo/$channelId'
    | '/api/public/webhooks/whatsapp/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicFlowResumeRoute: typeof ApiPublicFlowResumeRoute
  ApiPublicGuardianCronRoute: typeof ApiPublicGuardianCronRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLiveRoute: typeof ApiPublicLiveRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  ApiPublicCronCascadeTickRoute: typeof ApiPublicCronCascadeTickRoute
  ApiPublicHooksWhatsappWebhookRoute: typeof ApiPublicHooksWhatsappWebhookRoute
  ApiPublicWebhooksStevoChannelIdRoute: typeof ApiPublicWebhooksStevoChannelIdRoute
  ApiPublicWebhooksWhatsappChannelIdRoute: typeof ApiPublicWebhooksWhatsappChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quick-replies': {
      id: '/_authenticated/quick-replies'
      path: '/quick-replies'
      fullPath: '/quick-replies'
      preLoaderRoute: typeof AuthenticatedQuickRepliesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funnels': {
      id: '/_authenticated/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof AuthenticatedFunnelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cascades': {
      id: '/_authenticated/cascades'
      path: '/cascades'
      fullPath: '/cascades'
      preLoaderRoute: typeof AuthenticatedCascadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/flows/': {
      id: '/_authenticated/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof AuthenticatedFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live': {
      id: '/api/public/live'
      path: '/api/public/live'
      fullPath: '/api/public/live'
      preLoaderRoute: typeof ApiPublicLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guardian-cron': {
      id: '/api/public/guardian-cron'
      path: '/api/public/guardian-cron'
      fullPath: '/api/public/guardian-cron'
      preLoaderRoute: typeof ApiPublicGuardianCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flow-resume': {
      id: '/api/public/flow-resume'
      path: '/api/public/flow-resume'
      fullPath: '/api/public/flow-resume'
      preLoaderRoute: typeof ApiPublicFlowResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team/roles': {
      id: '/_authenticated/team/roles'
      path: '/team/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof AuthenticatedTeamRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/$memberId': {
      id: '/_authenticated/team/$memberId'
      path: '/team/$memberId'
      fullPath: '/team/$memberId'
      preLoaderRoute: typeof AuthenticatedTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/features': {
      id: '/_authenticated/settings/features'
      path: '/features'
      fullPath: '/settings/features'
      preLoaderRoute: typeof AuthenticatedSettingsFeaturesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/feature-flags': {
      id: '/_authenticated/settings/feature-flags'
      path: '/feature-flags'
      fullPath: '/settings/feature-flags'
      preLoaderRoute: typeof AuthenticatedSettingsFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reports/conversations': {
      id: '/_authenticated/reports/conversations'
      path: '/conversations'
      fullPath: '/reports/conversations'
      preLoaderRoute: typeof AuthenticatedReportsConversationsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/cascades': {
      id: '/_authenticated/reports/cascades'
      path: '/cascades'
      fullPath: '/reports/cascades'
      preLoaderRoute: typeof AuthenticatedReportsCascadesRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/broadcasts': {
      id: '/_authenticated/reports/broadcasts'
      path: '/broadcasts'
      fullPath: '/reports/broadcasts'
      preLoaderRoute: typeof AuthenticatedReportsBroadcastsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/inbox/$conversationId': {
      id: '/_authenticated/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof AuthenticatedInboxConversationIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/flows/$flowId': {
      id: '/_authenticated/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AuthenticatedFlowsFlowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/$contactId': {
      id: '/_authenticated/crm/$contactId'
      path: '/crm/$contactId'
      fullPath: '/crm/$contactId'
      preLoaderRoute: typeof AuthenticatedCrmContactIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/whatsapp-webhook': {
      id: '/api/public/hooks/whatsapp-webhook'
      path: '/api/public/hooks/whatsapp-webhook'
      fullPath: '/api/public/hooks/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicHooksWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cascade-tick': {
      id: '/api/public/cron/cascade-tick'
      path: '/api/public/cron/cascade-tick'
      fullPath: '/api/public/cron/cascade-tick'
      preLoaderRoute: typeof ApiPublicCronCascadeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flows/$flowId/runs': {
      id: '/_authenticated/flows/$flowId/runs'
      path: '/runs'
      fullPath: '/flows/$flowId/runs'
      preLoaderRoute: typeof AuthenticatedFlowsFlowIdRunsRouteImport
      parentRoute: typeof AuthenticatedFlowsFlowIdRoute
    }
    '/api/public/webhooks/whatsapp/$channelId': {
      id: '/api/public/webhooks/whatsapp/$channelId'
      path: '/api/public/webhooks/whatsapp/$channelId'
      fullPath: '/api/public/webhooks/whatsapp/$channelId'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stevo/$channelId': {
      id: '/api/public/webhooks/stevo/$channelId'
      path: '/api/public/webhooks/stevo/$channelId'
      fullPath: '/api/public/webhooks/stevo/$channelId'
      preLoaderRoute: typeof ApiPublicWebhooksStevoChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxConversationIdRoute: typeof AuthenticatedInboxConversationIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxConversationIdRoute: AuthenticatedInboxConversationIdRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsBroadcastsRoute: typeof AuthenticatedReportsBroadcastsRoute
  AuthenticatedReportsCascadesRoute: typeof AuthenticatedReportsCascadesRoute
  AuthenticatedReportsConversationsRoute: typeof AuthenticatedReportsConversationsRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsBroadcastsRoute: AuthenticatedReportsBroadcastsRoute,
  AuthenticatedReportsCascadesRoute: AuthenticatedReportsCascadesRoute,
  AuthenticatedReportsConversationsRoute:
    AuthenticatedReportsConversationsRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsFeatureFlagsRoute: typeof AuthenticatedSettingsFeatureFlagsRoute
  AuthenticatedSettingsFeaturesRoute: typeof AuthenticatedSettingsFeaturesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsFeatureFlagsRoute:
    AuthenticatedSettingsFeatureFlagsRoute,
  AuthenticatedSettingsFeaturesRoute: AuthenticatedSettingsFeaturesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedFlowsFlowIdRouteChildren {
  AuthenticatedFlowsFlowIdRunsRoute: typeof AuthenticatedFlowsFlowIdRunsRoute
}

const AuthenticatedFlowsFlowIdRouteChildren: AuthenticatedFlowsFlowIdRouteChildren =
  {
    AuthenticatedFlowsFlowIdRunsRoute: AuthenticatedFlowsFlowIdRunsRoute,
  }

const AuthenticatedFlowsFlowIdRouteWithChildren =
  AuthenticatedFlowsFlowIdRoute._addFileChildren(
    AuthenticatedFlowsFlowIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCascadesRoute: typeof AuthenticatedCascadesRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedFunnelsRoute: typeof AuthenticatedFunnelsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedQuickRepliesRoute: typeof AuthenticatedQuickRepliesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedCrmContactIdRoute: typeof AuthenticatedCrmContactIdRoute
  AuthenticatedFlowsFlowIdRoute: typeof AuthenticatedFlowsFlowIdRouteWithChildren
  AuthenticatedTeamMemberIdRoute: typeof AuthenticatedTeamMemberIdRoute
  AuthenticatedTeamRolesRoute: typeof AuthenticatedTeamRolesRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedFlowsIndexRoute: typeof AuthenticatedFlowsIndexRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCascadesRoute: AuthenticatedCascadesRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedFunnelsRoute: AuthenticatedFunnelsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedQuickRepliesRoute: AuthenticatedQuickRepliesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedCrmContactIdRoute: AuthenticatedCrmContactIdRoute,
  AuthenticatedFlowsFlowIdRoute: AuthenticatedFlowsFlowIdRouteWithChildren,
  AuthenticatedTeamMemberIdRoute: AuthenticatedTeamMemberIdRoute,
  AuthenticatedTeamRolesRoute: AuthenticatedTeamRolesRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedFlowsIndexRoute: AuthenticatedFlowsIndexRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicFlowResumeRoute: ApiPublicFlowResumeRoute,
  ApiPublicGuardianCronRoute: ApiPublicGuardianCronRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLiveRoute: ApiPublicLiveRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  ApiPublicCronCascadeTickRoute: ApiPublicCronCascadeTickRoute,
  ApiPublicHooksWhatsappWebhookRoute: ApiPublicHooksWhatsappWebhookRoute,
  ApiPublicWebhooksStevoChannelIdRoute: ApiPublicWebhooksStevoChannelIdRoute,
  ApiPublicWebhooksWhatsappChannelIdRoute:
    ApiPublicWebhooksWhatsappChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
